/*
Report Value :

https://wiki.openfoodfacts.org/API/Write#Add_the_Stores_where_bought

Si report mauvais value -> envoie un message a nous

On traite de notre coté -> envoie a OpenFoodFact


*/

import nodemailer from 'nodemailer'

let MAIL_ID = "Area2022dev@gmail.com";
let MAIL_PSSWORD = "qffcocegpaefcsba";

export const mailbis = () => {
    mail("pol_antoine.loiseau@yahoo.fr", "TEST")
}
export const mail = (destinataire : string, message : string) => {
    var transporter = nodemailer.createTransport({
        host: 'smtp.gmail.com',
        port: 465,
        secure: true,
        auth: {
            user: MAIL_ID,
            pass: MAIL_PSSWORD
        }
    });

    var mailOptions = {
        from: '"Area" <Area2022dev@gmail.com>',
        to: destinataire,
        subject: 'Automated Mail Generated by AREA',
        text: message
    };

    transporter.sendMail(mailOptions, function (error, info) {
        if (error) {
            console.log(error);
        } else {
            console.log('Email sent: ' + info.response);
        }
    });
}