name: Run jest tests (always)

on:
  push:
    branches: [ deployment, development, main ]
jobs:
  run_jest_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'
      - run: npm install
      - run: npm test