name: Run postman tests

on:
  push:
    branches: [ development ]
jobs:
  run_postman_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matt-ball/newman-action@master
        with:
          collection: ./tests/postman_heroku.json
