name: Run postman tests (deployment)

on:
  push:
    branches: [ deployment ]
jobs:
  run_postman_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matt-ball/newman-action@master
        with:
          collection: ./__tests__/postman.json
